Added a cert renewal bash script
populationgenomics/hail pull request #347
Opened 2024-08-22 02:06 UTC by nevoodoo

This script helps renew the TLS certificates as per https://populationgenomics.readthedocs.io/en/latest/hail.html#updating-tls-https-certificates by automating some of the steps that do not require user input.

2024-09-03 02:05 UTC, violetbrina commented
Could you add documentation (or a link to the existing cert renewal documentation) either in this repo or the script?
It would be good to update the docs to refer to this script as well as how to run it. Otherwise people will just default to manually updating the certs anyway.

2024-09-03 02:06 UTC, violetbrina requested changes
Add/update the cert renewal documentation

2024-09-19 00:49 UTC, nevoodoo commented
> Add/update the cert renewal documentation

This is done now :) 

See https://github.com/populationgenomics/team-docs/pull/165

2024-09-23 04:55 UTC, violetbrina approved these changes

2024-09-23 04:56 UTC, merged